### ISSUE TITLE
Android Studio warning: "Unchecked call to 'addChoice(String, T, boolean, FtcMenu)' as a member of raw type 'ftclib.FtcChoiceMenu'"

### ISSUE THREAD

**Issue by qwertychouskie** [trc492/FtcSamples#1]
I have no idea what it means, but Android Studio seems to not like it ;)

The code: https://github.com/FTCTeam10298/2017-18-code/blob/master/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OurM0Bot_Autonomous.java

P.S. Thanks for all the great code :D

**Comment by trc492** [comment]
When using the FtcChoiceMenu class, you need to specify what the object type the choices are. So for example, your code should declare the FtcChoiceMenu like this:
`
FtcChoiceMenu modeMenu = new FtcChoiceMenu<RunMode>("Run Mode", null, this);
FtcChoiceMenu allianceMenu = new FtcChoiceMenu<Alliance>("Alliance:", modeMenu, this);`

**Comment by qwertychouskie** [comment]
@trc492 Thanks!
