### ISSUE TITLE
Java 8 compiler question

### ISSUE THREAD

**Issue by shelbyRobots** [trc492/FtcSamples#3]
This is not an issue - just a question, but I couldn't find another way to ask.
I am helping mentor a junior high team, and we have a code base that has used FtcMenu and Dashboard from your excellent FtcSamples/Ftc3543Lib.
While getting things setup for Skystone, with latest AS, fork of latest FTC Skystone repo, and copy of latest Ftc3543Lib directory, I need to change source/target Compatibility to JavaVersion.VERSION_1_8 from 1_7 to get our TeamCode to link.
I tried to read up on this, and  I don't have access to team phones at moment.
Can you shed some light on where 1_8 features were added to the code, and more importantly tell whether or not the 1_8 compiler setting will affect whether new code will work on the various FTC approved phones?  We have 3 or 4 models of phones - we don't tend to primarily use the Samsung S5 or the Moto, but still occasionally do stuff with the older ones.
Thanks again for providing this resource!!

**Comment by trc492** [comment]
Our TRC library uses features such as method references which is only supported by compiler 1_8. 1_8 should be backward compatible with 1_7. In other words, 1_8 supports everything 1_7 supports. This is basically the Java language version. Java language constantly introduces new features that help simplifies the code and readability. Regarding on working with different phones, it is not the language version that's important, it is the SDK version. So targetSdkVersion and minSdkVersion are the ones you need to pay attention to. For example, the old ZTE phone can only support Sdk level 19. So minSdkVersion cannot be higher than 19 if you want to use ZTE as your Robot Controller phone. Hope that answers all your questions.
